### PR TITLE
Fixes #3 - Insert 'caret' to make scanning at index 0 faster.

### LINKED ISSUE #3: [performance] Regex matches inefficiently find irrelevant hits that get culled out right away.
This issue in kOS project : https://github.com/KSP-KOS/KOS/pull/2135
seems to imply that TinyPG itself can be edited to improve its regex performance in the scanner.

Example Text:
```
set   ident  to 1234 * sqrt(5432.1).[EOF]
             ^
             |
             |
    Imagine the Scanner's startpos is currently here
    because the scanner has already tokenized this much
    so far:
        set[whitespace skipped]ident[whitespace skipped]
```
That means the substring of the input file the scanner hasn't consumed yet is this:
```
to 1234 * sqrt(5432.1).[EOF]
^
```
And the zeroth position of that subset is where the caret is.

The Scanner currently does this in a for loop, inside LookAhead():
- For each scantoken rule (regex pattern) defined in the grammar file:
  - Try to find a match within the remaining substring  (`to 1234 * sqrt(5432.1)[EOF]` in the above example).
  - If a match is found **AND that match started at index 0** and it is longer than the longest match so far:
    - Then this becomes the new match so far.
- If no matches were found in the above loop, issue an error message - unexpected character.

But notice the bold text above.  Only matches that start at index 0 count, but the way it implements this is to find the matches at higher indeces, but then it immediately throw them away.  This is very inefficient, as discovered by @tsholmes.  For example, if the scanner was looking at the above example, the rule to match `INTEGER` will find a hit at index 3 on `1234`, but since that's not at index 0, it will be thrown out.  The rule to match `MULTIPLY` will find a hit on the substring `* at index 8`, but since that's not at index 0, it doesn't count and gets thrown out.  It will also find a hit for `IDENTIFIER` on the substring `sqrt` at index 10, but since that's not at index 0, it doesn't count and gets thrown out.  etc, etc, etc.  The only match that doesn't get thrown away is the one to find the keyword `TO`, which is kept because it was at index zero.

If you imagine a large file, this is a lot of matching that just gets thrown away right away.

By inserting an implied caret ("^") into the regex before running Regex.Match(), the Match routine itself can be told not to bother with any matches that don't start at index zero.  Then instead of getting the match and immediately throwing it away, it just won't find the match in the first place.

### PR DESCRIPTION
**Pull request by Dunbaratu**
See explanation in issue #3

### CODE REVIEW

File: TinyPG/Compiler/TerminalSymbol.cs [hunk 1]
```diff
@@ -27,7 +27,25 @@ public TerminalSymbol(string name)
...
+            // literal rather than a bit of code or a variable identifier
+            // containing the pattern:
+            int insertIndex = 0;
+            string patternWithCaret = pattern;
+            if (pattern.StartsWith("@\"")) // string literal starting with @"
+                insertIndex = 2;
+            else if (pattern.StartsWith("\"")) // string literal starting with "
+                insertIndex = 1;
+            if (pattern[insertIndex] != '^')
+                patternWithCaret = pattern.Insert(insertIndex, "^");
```
Comment (tsholmes) [inline TinyPG/Compiler/TerminalSymbol.cs]: I think here we actually want to wrap the entire existing expression into a group `^(existing_regex)` because if the regex is something like `true|false` then adding a caret at the start will only enforce that `true` is at the beginning of the line, but false could be anywyere. We'll actually probably want to use a non-capturing group in case they are using the group indexes for matching, so like `^(?:existing_regex)`

Comment (Dunbaratu) [reply TinyPG/Compiler/TerminalSymbol.cs]: Okay that's a good idea.

**Review by tsholmes — APPROVED** [review]
LGTM!

**Comment by Dunbaratu** [comment]
Good point.  I'll have to amend this PR tomorrow.  I just don't think of Scanner.cs, Parser.cs, and ParseTree.cs as being "source code" because of how they're generated, so I forget to include them in the PR.
